services:
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: whispers
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: me@samuel.dev
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "10000:80"
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
