#!/bin/bash

set -e

ACCOUNT_ID=661790212808
TAG_NAME=$1

aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/whispers-back-dev-worker2:$TAG_NAME
