rootProject.name = "whispers-back"
include("whispers-domain")
include("whispers-app")
include("whispers-adapter-web")
include("whispers-adapter-jpa")
include("whispers-adapter-dynamo")
include("whispers-adapter-sns")
include("whispers-adapter-sqs")
include("whispers-bin-web-jpa")
include("whispers-bin-web-dynamo")
include("whispers-bin-worker-jpa")
include("whispers-bin-worker-dynamo")
