#!/bin/bash

set -e

for i in $(seq 1 5); do
    AWS_PAGER= aws lambda invoke \
        --function-name "whispers-python-lambdas-$1" \
        --invocation-type "Event" \
        --cli-binary-format raw-in-base64-out \
        --no-paginate \
        response.out
done
