#!/bin/sh

set -e

rm lambda.zip
pip install --target packages aws-psycopg2
pip install --target packages amazon-dax-client
pip install --target packages Faker
cd packages
zip -r ../lambda.zip .
cd ..
zip lambda.zip *.py
