#!/bin/sh

set -e

rm lambda.zip
pip install --target packages aws-psycopg2
cd packages
zip -r ../lambda.zip .
cd ..
zip lambda.zip lambda_rds.py
zip lambda.zip lambda_dynamo.py
zip lambda.zip sns_publisher.py
